# Cloudflare Workers configuration for Hidden Walnuts Portfolio

name = "hidden-walnuts-portfolio"
compatibility_date = "2024-01-15"
main = "_worker.js"

# Environment variables (you'll need to set these via CLI or dashboard)
[vars]
# These will be set during deployment
# CLOUDFLARE_ACCOUNT_ID = "your-account-id"
# CLOUDFLARE_API_TOKEN = "your-api-token"

# KV Namespaces
[[kv_namespaces]]
binding = "PORTFOLIO_KV"
id = "6f7bb7f0d8064c7d8d3dbc7ba320ad6b"
preview_id = "9da2c6a1d97543c9b5edfbc084e68203"

# Routes for custom domain (hiddenwalnuts.com)
[[routes]]
pattern = "hiddenwalnuts.com/*"
zone_name = "hiddenwalnuts.com"

[[routes]]
pattern = "www.hiddenwalnuts.com/*" 
zone_name = "hiddenwalnuts.com"

# No build configuration needed for worker-only architecture