name = "hidden-walnuts"
compatibility_date = "2024-01-01"
# Required for Next.js on Cloudflare Pages - trying with do_not_populate_process_env in dashboard
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @cloudflare/next-on-pages@1"

[build.upload]
format = "directory"

[pages]
pages_build_output_dir = ".next" 