name = "categories-api"
main = "src/index.ts"
compatibility_date = "2024-04-29"

kv_namespaces = [
  { binding = "CATEGORIES", id = "54488ea74dd245609cb84d643d9023f6" }
]
r2_buckets = [
  { binding = "IMAGES", bucket_name = "hiddenwalnuts-bucket" }
] 