name = "auth-api"
main = "src/index.ts"
compatibility_date = "2024-03-25"

[env.development]
name = "auth-api-dev"
ENVIRONMENT = "development"
ADMIN_USERNAME = "REPLACE_WITH_SECURE_USERNAME"  # Replace this with a secure username
ADMIN_PASSWORD = "REPLACE_WITH_SECURE_PASSWORD"  # Replace this with a secure password

[env.production]
name = "auth-api"
ENVIRONMENT = "production"
ADMIN_USERNAME = "REPLACE_WITH_SECURE_USERNAME"  # Replace this with a secure username
ADMIN_PASSWORD = "REPLACE_WITH_SECURE_PASSWORD"  # Replace this with a secure password

[[kv_namespaces]]
binding = "AUTH_STORE"
id = "54488ea74dd245609cb84d643d9023f6"
preview_id = "54488ea74dd245609cb84d643d9023f6" 